### ISSUE TITLE
Error "user lacks privilege or object not found" after table creation

### ISSUE THREAD

**Issue by artem78** [prrvchr/HsqlDriverOOo#1]
Hi @prrvchr !

I hope you're not tired of me, but I have another problem. This time with HyperSQLOOo extension.

I have installed both jdbcDriverOOo and HyperSQLOOo to LibreOffice as described [here](https://prrvchr.github.io/HyperSQLOOo/) for using modern HsqlDB 2.7.

I created new database with embedded HsqlDB with one simple table.

![Снимок экрана в 2023-11-26 21-29-33](https://github.com/prrvchr/HyperSQLOOo/assets/8585304/8ede8bfa-3614-45d9-95f0-5c4b1eb88ec8)

![Снимок экрана в 2023-11-26 21-30-07](https://github.com/prrvchr/HyperSQLOOo/assets/8585304/5b4ea6d7-9a1c-4d1c-a9fb-d7f069d40b17)

![Снимок экрана в 2023-11-26 21-30-22](https://github.com/prrvchr/HyperSQLOOo/assets/8585304/f2809660-036f-4958-bdb1-98189fd658db)

Next when I open this table for data insertion this error shows:

![Снимок экрана в 2023-11-26 21-30-52](https://github.com/prrvchr/HyperSQLOOo/assets/8585304/56a9c683-1781-400f-8862-eb9674e32818)

Error details:
```
SQL Status: 42501
Error code: -5501
```

I run this SQL query manually to show all tables:

```sql
SELECT *
FROM   INFORMATION_SCHEMA.TABLES
```

But my table not listed in the output.

Issue described here reproduced both in Linux and Windows, also with latest LibreOffice 7.6.3 release.

Sample database file: [mydb.odb.zip](https://github.com/prrvchr/HyperSQLOOo/files/13467940/mydb.odb.zip)

**Comment by prrvchr** [comment]
Hi artem78,

This is not an error, we cannot create a table in the **INFORMATION_SCHEMA** schema, this is a schema reserved for the system and we must either create a new schema or use the default **PUBLIC** schema.

![SaveAs](https://github.com/prrvchr/HyperSQLOOo/assets/7834336/08e69710-9d6f-4c45-b118-cae1678d5559)

It is true that it would be good if the HyperSQLOOo driver gave an error rather than letting people believe that the table was created... I will try to correct this...

**Comment by prrvchr** [comment]
I just pushed **jdbcDriverOOo version 1.0.7**. Now an error appears instead of making it appear that the table was created...
Thanks for helping to improve the extensions...

**Comment by artem78** [comment]
Thanks.
